#!/usr/bin/with-contenv bash

chmod 755 /bin/quantica /bin/qexec /etc/periodic/*

mkdir /config/log/quotes

# copy config files
if [ -d "/config/quantica" ]; then  
  echo "Keeping volume files..."
else
  echo "Loading from defaults..."
	cd /quantica
	mv quantica /config/
fi

# perform a system check
cd /
quantica -ts quantica.SystemCheck -e CHECK
